# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
